CREATE DATABASE EMPOWER;
USE EMPOWER;

CREATE TABLE ELIGIBILITY(AGE INT, INCOME INT, EMP_STATUS VARCHAR(20),CITIZENSHIP VARCHAR(20), PID INT , foreign key(PID) 
references POLICY(PID));
ALTER TABLE ELIGIBILITY
ADD CONSTRAINT fk_policy_pid FOREIGN KEY (PID) REFERENCES POLICY(PID);
SELECT * FROM ELIGIBILITY;
SHOW TABLES;
DESC  ELIGIBILITY;
CREATE TABLE POLICY(PNAME VARCHAR(50), PID INT PRIMARY KEY);
ALTER TABLE POLICY MODIFY COLUMN PNAME VARCHAR(150);
CREATE TABLE ASSISTANCE(FINANCIAL_ASSISTANCE bool,HEALTHCARE_BENEFITS BOOL, EDUCATION BOOL,
HOUSING_SUPPORT BOOL, ASSIS_ID INT, foreign key(ASSIS_ID) references POLICY(PID));
CREATE TABLE DEMOGRAPHIC_FOCUS(FAMILY BOOL,SENIORS BOOL , STUDENTS BOOL, PwD BOOL, GENDER VARCHAR(20), DID INT,
 foreign key(DID) references POLICY(PID));
CREATE TABLE LOCATION(CITY VARCHAR(25), RURAL BOOL, URBAN BOOL, DISASTER_RELIEF BOOL, LID INT,
 foreign key(LID) REFERENCES POLICY(PID));
 CREATE TABLE SPECIAL_CIRCUMSTANCES(VETERANS BOOL, INDIGENEOUS BOOL, REFUGEES BOOL, CID INT
 , FOREIGN KEY(CID) REFERENCES POLICY(PID));
SHOW TABLES;
DESC POLICY;
SET SQL_SAFE_UPDATES = 1;
SHOW VARIABLES LIKE 'secure_file_priv';
LOAD DATA INFILE "C:\Users\91860\OneDrive\Desktop\trees\POLICY.csv"
INTO TABLE POLICY
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
SELECT * FROM POLICY;

																							